- pom.xml
- src/main/java/bdv/img/cache/VolatileGlobalCellCache.java
- src/main/java/bdv/img/cache/VolatileImgCells.java
This enables to index cache cells for larger images.  My story was this: showing a volume of 200,000x150,000x8,000px in blocks of 64x64x1px blocks failed because it had to be able to index more than 27&times; too many cache cells.  It also did not fail in a user friendly way but generated overflows into negative cell-coordinates---pretty ugly.  I am not sure how much that breaks outside of core and my own projects because I also had to move away from `ListImg`, @tpietzsch?
> raised VolatileImgCells cell index from int to long

- src/main/java/bdv/BehaviourTransformEventHandler3D.java
I ran into a case where `BehaviourTransformEventHandler3D.setCanvasSize` gets called with (0, 0) size. When this occurs, we should perform a new transformation because it will result in a "Matrix is singular" exception. In practice, this call happens at an intermediate layout step, after which the canvas will be resized again to non-zero size.
> Avoid exception when canvas size is zero

- src/main/java/bdv/tools/brightness/BrightnessDialog.java
- src/main/java/bdv/tools/brightness/SetupAssignments.java
When a checkbox is unchecked and removes a minmax setup from a group that only has the one setup left, rather than remove and re-add it to the bottom, it now stays where it is.
The old behavior was somewhat confusing and has no apparent usefulness, other than reordering the minmax groups.
Old Behavior:
New Behavior:
> Change BrightnessDialog checkbox behavior

- src/main/java/bdv/viewer/ViewerPanel.java
Before only toggling interpolation was possible.
In my use case I have a state handler object that handles the shared state of multiple viewers. In order to change the interpolation method consistently, I need to be able to set the interpolation method directly instead of toggling/cycling through the interpolation method values.
> Set interpolation directly

- src/main/java/bdv/util/Prefs.java
- src/main/java/bdv/viewer/ViewerPanel.java
Currently, the `Prefs` instance is initialized from a config file in the user home directory, or from a default if that is not found. There is no way to programmatically change the preferences. I am currently working on orthoviews, and having mouse coordinates and the multibox displayed in each of the `ViewerPanel`s is unnecessary or even wrong. I propose to add setters for the preferences, so these can be set from within code.
> Set prefs programmatically

- src/main/java/bdv/viewer/ViewerPanel.java
I have ortho slices in a 3D viewer window that reflect the contents of three (orthogonal) `ViewerPanel`s. These ortho slices show textures that are generated whenever the `renderTarget` notifies its listeners that are added through `ViewerPanel.addRenderTransformListener`. In order to render the image onto the ortho slice, I need to have access to `renderTarget`.
> Expose renderTarget

- src/main/java/bdv/tools/VisibilityAndGroupingDialog.java
This bug occurs with `ViewerFrame`s created e.g. in Mastodon. It does not happen for `ViewerFrame`s opened with `BdvFunction.show()`.
If a source is appended to the viewerframe - e.g. the bounding-box source - it is not possible to close the viewframe without triggering the exception pasted below.
Somehow, when the frame is closing, the `VisibilityAndGroupingDialog` instance goes through the buttons list after it has been cleared and tries to set the selected state of one.
This ad-hoc fix simply checks that there is a button to set the state of before doing so.
To see this bug in action, check the branch 'bbox' of the trndy/mastodon-tracking artifact. Creating a bounding-box during the detection sequence wizard generates this bug.
``` java
Exception in thread "AWT-EventQueue-0" …
```
> Fix exception when closing a view frame after adding a source.

- src/main/java/bdv/export/ProposeMipmaps.java
- src/main/java/bdv/util/MipmapTransforms.java
I ran into what I believe is an incorrect behavior of `getBestMipMapLevel()` when visualizing non-isotropic data. In my case the pixel resolution is 4x4x40nm, and the downsampling factors for the mipmaps are:
```
0: [1,1,1]
1: [2,2,1]
2: [4,4,1]
3: [8,8,1]
4: [16,16,2] 
```
Determining the best mipmap level works properly in orthogonal XY view, but the problem occurs when the view is rotated (especially in orthogonal XZ or ZY views). Due to the same Z scaling factor in the first 4 levels, it picks either scale level 4 when zooming out a lot, or scale level 0 when zooming closer. Sometimes it picks scale level 3 over scale level 4 because of [this heuristic](https://github.com/bigdataviewer/bigdataviewer-core/blob/b60e6079c592f0523a3315099d5c34330e0e78ae/src/main/java/bdv/util/MipmapTransfo …
> Fix determining best mipmap level for non-isotropic data

- src/main/java/bdv/viewer/state/ViewerState.java
This is useful when sources are managed from outside and not all sources might be present in the current state. For reduced code duplication, the existing overload `getBestMipMapLevel( AffineTransform3D, int )` delegates to the newly created overload.
> Query best mipmap level from source directly.

- pom.xml
- src/main/java/bdv/viewer/Interpolation.java
- src/test/java/bdv/viewer/InterpolationTest.java
Toggling interpolation now simply becomes `interpolation.next()` instead of `NLINEAR.equals(interpolation) ? NEARESTNEIGHBOR : NLINEAR`.
@tpietzsch If this is something that you would like, I will add a short doc string with an explanation before this gets merged.
> Add `next()` method to Interpolation enum

- src/main/java/bdv/ui/sourcegrouptree/SourceGroupEditor.java
* setting no `editingIcon` when in edit mode makes the group name disappear on Linux
* this fix adds a call to the default `determineOffset` method (where the icon is set)
@tpietzsch Let me know if I should look for an alternative solution.
> SourceGroupEditor: Fix bug in Linux when editing group name

- src/main/java/bdv/ui/BdvDefaultCards.java
- src/main/java/bdv/ui/MouseWheelScrollListener.java
* this improves scrolling on the list of sources and groups - if the inner scrollbar is at the end (or if there is no scrollbar at all), the whole cards panel will be scrolled
Only tested on Linux so far.
> BdvDefaultCards: Dispatch scroll event to parent JScrollPane

- src/main/java/bdv/export/ProposeMipmaps.java
If numBits turns negative, it suggests completely wrong blocksizes, example below:
final ViewSetup setup = new ViewSetup( 0, "0", new FinalDimensions( 2048, 2048, 1 ), new FinalVoxelDimensions( "um", 0.004488999829630086, 0.004488999829630086, 1.0 ), null, null, null, null );
final ExportMipmapInfo e = ProposeMipmaps.proposeMipmaps( setup );
for ( int l = 0; l < e.getNumLevels(); ++l )
System.out.println( Util.printCoordinates( e.getSubdivisions()[l]  ) );
/*
Yields:
(128, 64, -2147483648)
(64, 64, 1)
(64, 64, 1)
(64, 32, 2)
With fix:
(64, 64, 1)
(64, 64, 1)
(64, 64, 1)
(64, 32, 2)
*/
> Fix a bug in proposeMipMaps.

- pom.xml
Remove hard-coded versions as well as overridden version properties.
Fixes https://github.com/fiji/fiji/issues/256.
/cc @tischi
> POM: update parent to pom-scijava-29.2.0

- src/main/java/net/imglib2/display/RealARGBColorConverter.java
`ClassCopyProvider` is used to create `RealARGBColorConverter`. Unfortunately an imglib2 pixel is used as the key. ClassCopyProvider keeps the key (imglib2 pixel) in memory. The pixel holds a reference to the image. Hence prevents the image from being garbage collected.
This can prevent many images shown in BDV from being garbage collected. As every new pixel value is a new key, and will kept.
> Important: Fix memory leak

- src/main/java/bdv/tools/HelpDialog.java
- src/main/java/bdv/tools/RecordMaxProjectionDialog.java
- src/main/java/bdv/tools/RecordMovieDialog.java
- src/main/java/bdv/tools/VisibilityAndGroupingDialog.java
- src/main/java/bdv/tools/brightness/BrightnessDialog.java
- src/main/java/bdv/ui/BdvDefaultCards.java
- src/main/java/bdv/util/DelayedPackDialog.java
- src/main/java/bdv/util/MemoryFixedDialog.java
- src/main/java/bdv/viewer/ViewerPanel.java
This PR fixes three reasons that prevented BDV to be properly garbage collected.
1. Using the method `pack()` of `JFrame` or `JDialog` will cause the window be refrenced (and prevent) garbage collection until `dispose()` is called. This is fixed by introducing `MemoryFixedDialog`. The dialog uses "DISPOSE_ON_CLOSE", and avoid's calling `pack()` as long as the dialog is invisible.
2. Remove unnecessary reference from `PainterThread` to `ViewerPanel`.
3. BdvDefaultCards, introduce weak reference when listening for keyboard focus.
Code that triggers the OutOfMemoryException (fixed by this PR):
```java
for ( int i = 0; i < 60; i++ )
{
System.out.println( i );
BdvFunctions.showOverlay( new BdvOverlay()
{
private final byte[] oneGigaByte = new byte[ 1 << 30 ];
@Override
protected void draw( …
```
> Fix Big Data Viewer Garbage Collection

- src/main/java/bdv/tools/transformation/TransformedSource.java
- src/main/java/bdv/util/RealRandomAccessibleSource.java
- src/main/java/bdv/viewer/Source.java
- src/main/java/bdv/viewer/render/VisibilityUtils.java
a default implementation preserves the current behavior
> add flag to skip renderer's bounding box intersection

- src/main/java/bdv/BigDataViewer.java
- src/main/java/bdv/util/Prefs.java
- src/main/java/bdv/viewer/ViewerPanel.java
- src/main/java/bdv/viewer/overlay/SourceInfoOverlayRenderer.java
Addresses #109
I realised that positioning the source and group names below the coordinates does an even better job in terms of not clashing with them than left alignment. 
It has the additional benefit of keeping out of the way of the multi-box overlay. 
I also like visually that all the text information is shown as one block.
`Prefs.positionTextOverlayBelowCoordinates( true );`
I don't really like the name `positionTextOverlayBelowCoordinates` as it is very verbose, but I did not have a shorter idea right now.
What do you think?
> Optionally position source name below coordinates

- src/main/java/bdv/img/imaris/Imaris.java
Avoids invalid xml field in case no channel name is found in imaris ims file.
> check for null field in imaris file

- src/main/java/bdv/export/ProposeMipmaps.java
This improves the algorithm for suggesting and subsampling factors / chunk sizes:
* We don't consider dimensions with size 1 for (further) downsampling
* We use the dimensions of downsampled image in chunk size determination. For example we will never suggest chunk size [16,16,16] for 2D images. Knowing that dim[Z]==1, the cell size will be limited to 1 in Z.
This should resolve https://github.com/bigdataviewer/bigdataviewer_fiji/issues/21
> Improve suggested subsampling factors / chunk sizes for 2D images

- src/main/java/bdv/tools/InitializeViewerState.java
- src/main/java/bdv/tools/bookmarks/BookmarkTextOverlayAnimator.java
- src/main/java/bdv/tools/bookmarks/BookmarksEditor.java
- src/main/java/bdv/tools/boundingbox/AbstractTransformedBoxSelectionDialog.java
- src/main/java/bdv/tools/boundingbox/TransformedBoxEditor.java
- src/main/java/bdv/tools/boundingbox/TransformedBoxOverlaySource.java
- src/main/java/bdv/tools/boundingbox/TransformedBoxSelectionDialog.java
- src/main/java/bdv/tools/boundingbox/TransformedRealBoxSelectionDialog.java
- src/main/java/bdv/tools/transformation/ManualTransformation.java
- src/main/java/bdv/tools/transformation/ManualTransformationEditor.java
- src/main/java/bdv/ui/BdvDefaultCards.java
- src/main/java/bdv/ui/splitpanel/SplitPaneOneTouchExpandTrigger.java
- src/main/java/bdv/ui/splitpanel/SplitPanel.java
- src/main/java/bdv/viewer/AbstractViewerPanel.java
- src/main/java/bdv/viewer/InteractiveDisplay.java
- src/main/java/bdv/viewer/InteractiveDisplayCanvas.java
- src/main/java/bdv/viewer/NavigationActions.java
- src/main/java/bdv/viewer/ViewerFrame.java
- src/main/java/bdv/viewer/ViewerPanel.java
* Split out abstract base class from `AbstractViewerPanel` from `ViewerPanel`.
`AbstractViewerPanel` is used instead of ViewerPanel where possible.
This will allow to re-use bookmark, bounding box, manual transform tools in BigVolumeViewer.
* Use scijava-listeners for `ViewerPanel` listeners
* Reduce usage of deprecated `bdv.viewer.state.ViewerState`
* make `AbstractViewerPanel.align(...)` public
> AbstractViewerPanel

- src/main/java/bdv/tools/boundingbox/TransformedBoxOverlaySource.java
removes a print statement.
I'm using this awesome functionality in n5-viewer now, and ran into this.
> suppress output in TransformedBoxOverlaySource.repaint

- src/main/java/bdv/viewer/render/PainterThread.java
- src/test/java/bdv/viewer/render/PainterThreadGarbageCollectionTest.java
This PR changes the PainterThread to use WeakReference. This ensure that the paintable can be garbage collected without the painter thread intervening.
The PR also adds a unit test to ensure that the garbage collection works as expected.
Additionally notify() is replaced with notifyAll(). It doesn't make a difference in our case. But notifyAll() is the preferred method to use because it more reliable wakes up the waiting threads.
> Make sure the PainterThread does not cause a memory leak

- src/main/java/bdv/AbstractSpimSource.java
This is for BigStitcher to easily update transforms in `SpimData`. `AbstractSpimSource` caches transformations for all resolution levels of the current time-point. Unless the time-point changes, these transformations are not updated if `ViewRegistrations` in `SpimData` are changed. The new `AbstractSpimSource::reload` allows to trigger a reload.
> Add AbstractSpimSource::reload method

- src/main/java/bdv/tools/transformation/ManualTransformationEditor.java
See https://imagesc.zulipchat.com/#narrow/stream/327326-BigDataViewer/topic/Manual.20transform.20editor
> ManualTransformationEditor with a custom set of sources

- src/main/java/bdv/export/WriteSequenceToHdf5.java
This is required for https://github.com/bigdataviewer/bigdataviewer_fiji/issues/29
> Remove obsolete check for UnsignedShortType when exporting to HDF5
